name: Run Test with Agent

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDKs
        uses: actions/setup-java@v4
        with:
          java-version: |
            17
            26
          distribution: 'temurin'
          cache: 'maven'

      - name: Download agent jars from GitHub Packages
        env:
          AGENT_VERSION: "1.3"
        run: |
          if [ -z "$AGENT_VERSION" ]; then
            echo "::error::FIXATE_AGENT_VERSION is not set"
            exit 1
          fi

          curl -fu "${{ github.repository_owner }}:${{ secrets.FIXATE_PACKAGES_ACCESS_TOKEN }}" \
            -L "https://maven.pkg.github.com/fixate-dev/Fixate/com/example/fixate-agent/${AGENT_VERSION}/fixate-agent-${AGENT_VERSION}.jar" \
            -o fixate-agent.jar

          curl -fu "${{ github.repository_owner }}:${{ secrets.FIXATE_PACKAGES_ACCESS_TOKEN }}" \
            -fL "https://maven.pkg.github.com/fixate-dev/Fixate/com/example/fixate-agent/${AGENT_VERSION}/fixate-agent-${AGENT_VERSION}-bootstrap.jar" \
            -o fixate-agent-bootstrap.jar

      - name: Install
        run: ./mvnw -B -ntp -Dtoolchain.skip install -U -DskipTests=true

      - name: Run tests with agent
        env:
          MAVEN_OPTS: "-javaagent:${{ github.workspace }}/fixate-agent.jar -Xmx16g --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/sun.security.jca=ALL-UNNAMED"
        run: ./mvnw -B -ntp -Dtoolchain.skip test -Dsurefire.toolchain.version=17 -Dfixate.depth=0
        
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ./reports/
