name: Run Test with Agent

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "zulu"

      - name: Download agent jars from GitHub Packages
        env:
          AGENT_VERSION: "${{ vars.FIXATE_AGENT_VERSION }}"
        run: |
          # Download Fixate agent
          curl -u "${{ github.repository_owner }}:${{ secrets.FIXATE_PACKAGES_ACCESS_TOKEN }}" \
            -L "https://maven.pkg.github.com/fixate-dev/Fixate/com/example/fixate-agent/${AGENT_VERSION}/fixate-agent-${AGENT_VERSION}.jar" \
            -o fixate-agent.jar

          # Download bootstrap jar
          curl -u "${{ github.repository_owner }}:${{ secrets.FIXATE_PACKAGES_ACCESS_TOKEN }}" \
            -fL "https://maven.pkg.github.com/fixate-dev/Fixate/com/example/fixate-agent/${AGENT_VERSION}/fixate-agent-${AGENT_VERSION}-bootstrap.jar" \
            -o fixate-agent-bootstrap.jar

      # - name : install guava
      #   run: mvn install -DskipTests

      - name: Run tests with agent
        env:
          MAVEN_OPTS: "-javaagent:./fixate-agent.jar"
        run: ./mvnw test -DargLine="-Xmx16g fixate.depth=0"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: ./reports/
